// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_3 = "CgkI_K_M8_AfEAIQBA"; // <GPGSID>
        public const string achievement_4 = "CgkI_K_M8_AfEAIQBQ"; // <GPGSID>
        public const string achievement_5 = "CgkI_K_M8_AfEAIQBg"; // <GPGSID>
        public const string achievement_6 = "CgkI_K_M8_AfEAIQBw"; // <GPGSID>
        public const string achievement_7 = "CgkI_K_M8_AfEAIQCA"; // <GPGSID>
        public const string achievement_8 = "CgkI_K_M8_AfEAIQCg"; // <GPGSID>
        public const string achievement_9 = "CgkI_K_M8_AfEAIQDA"; // <GPGSID>
        public const string achievement_16 = "CgkI_K_M8_AfEAIQEw"; // <GPGSID>
        public const string achievement_13 = "CgkI_K_M8_AfEAIQEA"; // <GPGSID>
        public const string achievement_10 = "CgkI_K_M8_AfEAIQDQ"; // <GPGSID>
        public const string achievement_11 = "CgkI_K_M8_AfEAIQDg"; // <GPGSID>
        public const string achievement_12 = "CgkI_K_M8_AfEAIQDw"; // <GPGSID>
        public const string achievement_first_blood = "CgkI_K_M8_AfEAIQAg"; // <GPGSID>
        public const string achievement_14 = "CgkI_K_M8_AfEAIQEQ"; // <GPGSID>
        public const string achievement_15 = "CgkI_K_M8_AfEAIQEg"; // <GPGSID>
        public const string achievement_object_is_null = "CgkI_K_M8_AfEAIQCQ"; // <GPGSID>
        public const string achievement_tan_90 = "CgkI_K_M8_AfEAIQCw"; // <GPGSID>
        public const string achievement = "CgkI_K_M8_AfEAIQAQ"; // <GPGSID>
        public const string achievement_2 = "CgkI_K_M8_AfEAIQAw"; // <GPGSID>

}

